# PID
kp: 1.2 #0.5 # 1.4 works well and more quick
ki: 0.0006  # 0.0002
kd: 0.00015 #0.00005

kp_yaw: 0.1
ki_yaw: 0.0002
kd_yaw: 0.00005

tolerance: 0.30

# 6,3,2 is the path tried
# 10, 4 ,2 gives only one waypoint
