# This is the default method
hill_climbing:
  iterations: 400
  desired distance: 1.1
  restarts: 5

# Change run to true/false, to execute SA or simple Hill Climbing
simulated_annealing:
  run: false
  temperature: 1000
  cooling_rate: 0.999
  absolute_temperature: 0.00001
