#####
rfid:
  shape: circular #orthogonal
  range: 2 # in metres
  hfov: 60 # degrees
  vfov: 30 # degrees
  direction: # 	A vector pointing in the direction of the sensor on the drone
    x: 1
    y: 0
    z: 0

uav:
  footprint_radius: 0.4 # in metres
  safety_offset: 0.10 # in metres

world:
  min_obstacle_height: 0.05 # in metres

coverage:
  subsampling_step: 0.75 # in metres
  method: slice #lift # Method for reverting to 6D points again
