#####
rfid:
  shape: orthogonal #circular
  range: 2 # in metres
  hfov: 60 # degrees
  vfov: 30 # degrees

uav:
  footprint_radius: 0.4 # in metres
  safety_offset: 0.3 # in metres

world:
  min_obstacle_height: 0.05 # in metres

coverage:
  method: slice #lift
