# PID
# the I is always zero, as in the simulation it is a perfect world, where there is no wind or other factor that change the stability of the drone
# https://robotics.stackexchange.com/questions/9554/quadcopter-pid-algorithm
# x position
x_kp: 0.7
x_ki: 0
x_kd: 0.000015

# y position
y_kp: 0.7
y_ki: 0
y_kd: 0.000015

# z position
z_kp: 2.5
z_ki: 0
z_kd: 0.00025

# yaw
yaw_kp: 0.05
yaw_ki: 0
yaw_kd: 0.00005

# Tolerance of the distance from the waypoints, to be accepted
tolerance: 0.25
