# PID
# the I is always zero, as in the simulation it is a perfect world, where there is no wind or other factor that change the stability of the drone
# https://robotics.stackexchange.com/questions/9554/quadcopter-pid-algorithm

# Tolerance of the distance from the waypoints, to be accepted
tolerance:
  xy: 0.30
  z: 0.15
  yaw: 0.25

# Max speed allowed for the drone to move in x,y,z,yaw (m/s)
max_speed:
  translational: 1 # m/sec
  rotational: 3 # rad/sec
