# Initial States #

# Position
x_pos: 1
y_pos: 0
z_pos: 0.2

# Orientation
roll: 0
pitch: 0
yaw: 0

# Number of particles
particles: 500

# Standard deviations for movement model
/movement/x_std_dev: 0.2
/movement/y_std_dev: 0.2
/movement/z_std_dev: 0.2

/movement/roll_std_dev: 0.2
/movement/pitch_std_dev: 0.2
/movement/yaw_std_dev: 0.2


# Frames
mapFrame: "map"
worldFrame: "world"
baseFootprintFrame: "base_footprint"
baseStabilizedFrame: "base_stabilized"
baseLinkFrame: "base_link"

transform_tolerance_time: 1.0

# Observation parameters / Raycasting
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_rand: 0.5
laser_z_max: 0.05
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
min_range: 0.01
max_range: 14
observation_threshold_trans: 0.3
observation_threshold_rot: 0.4
sensor_sample_distance: 0.2
