#fake_controllers.yaml

controller_list:
  - name: multi_dof_joint_trajectory_action
    type: MultiDofFollowJointTrajectory
    default: true
    joints:
      - virtual_joint

#controller_list:
#  - name: fake_Quadrotor_base_controller
#    joints:
#      - virtual_joint
