# The name of this file shouldn't be changed, or else the Setup Assistant won't detect it
###################################################################################
# MUST UPDATE IT!!!!
###################################################################################
#sensors:
# - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#   point_cloud_topic: /quad/camera_/depth/points
#   max_range: 10.0
#   frame_subsample: 1
#   point_subsample: 1
sensors:
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /depth_registered/image_raw
    queue_size: 5
    near_clipping_plane_distance: 0.3
    far_clipping_plane_distance: 5.0
    shadow_threshold: 0.2
    padding_scale: 4.0
    padding_offset: 0.03 # (in cm)
    filtered_cloud_topic: filtered_cloud # The topic on which the filtered cloud will be published (mainly for debugging). The filtering cloud is the resultant cloud after self-filtering has been performed.
